### ISSUE TITLE
pretrained/resnet101_v1c-e67eebb6.pth can not

### ISSUE THREAD

**Issue by ljjcoder** [google-research/semivl#8]

**Comment by ljjcoder** [comment]
Thanks for your excellent work! I ran the following script to conduct cityscapes experiments:
python experiments.py --exp 44 --run 0
However, the following problems were encountered:

![1706235537707](https://github.com/google-research/semivl/assets/40750189/3d428be7-a856-4a90-9364-085de6312447)
Where can I download resnet101_v1c-e67eebb6.pth?

**Comment by lhoyer** [comment]
You can download this checkpoint from UniMatch: https://github.com/LiheYoung/UniMatch#pretrained-backbone
