### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by SaSa-123** [google-research/semivl#9]
Thanks to the author for the wonderful work. I am a beginner. I installed your requirements and created a virtual environment with python version 3.7.13. When I ran pip install -r requirements.txt, I was prompted ERROR: Could not find a version that satisfies the requirement, how to solve it?
![Snipaste_2024-02-20_15-33-10](https://github.com/google-research/semivl/assets/79628470/78e43b2e-340a-4e7c-83f1-d0d6d98ba3c2)

**Comment by lhoyer** [comment]
Thank you for your interest in our work. It looks like your pip is outdated and does not know about the newer numpy version.

**Comment by SaSa-123** [comment]
> Thank you for your interest in our work. It looks like your pip is outdated and does not know about the newer numpy version. I would suggest to upgrade pip and try it again.

Thank you for your sincere reply! In addition, I would also like to ask how much memory is required to run this code on the CitySpace dataset?
![Snipaste_2024-02-20_22-42-00](https://github.com/google-research/semivl/assets/79628470/dea18506-9178-428f-8e42-5e474b31678c)

**Comment by lhoyer** [comment]
On Cityscapes, we trained the model with 8 x A100 (40 GB) GPUs, where each GPU has a batch size of 1 (see experiments.py at exp_id == 44.
